[package]
name = "pico-8"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = "0.14.14"
rlua = "0.20.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
image = "0.25.5"

[build-dependencies]
sdl3-sys = "0.4.5"
